---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2018/11/28 16:23
---

AssetManagerInjector={}
AssetManagerInjector.LoadAssetBundle=function()
    return function(a)
        print('Injector AssetbundleManager************')
    end,LuaInterface.InjectType.After
end
InjectByModule(AssetBundleManager,AssetManagerInjector)