---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2018/11/7 12:32
---
---@param enum1 TestLuaEnum
function TestEnum(enum1)
     print(enum1:ToString())
    local intE= enum1:ToInt()

    print(  intE,type(intE) )
    local enum2= TestLuaEnum.IntToEnum(2)
    print(enum2:ToString())
    if(enum1 == enum2) then
        print("enum2 == enum1")
    else
        print("enum2 ^= enum1")
    end
    if(enum1:Equals(2)) then
        print("enum1 == 2")
    else
        print("enum1 ^= 2")
    end





end