//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestClassAWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TestClassA), typeof(System.Object));
		L.RegFunction("Start", Start);
		L.RegFunction("New", _CreateTestClassA);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTestClassA(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TestClassA obj = new TestClassA();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TestClassA.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TestClassA obj = (TestClassA)ToLua.CheckObject<TestClassA>(L, 1);
			obj.Start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

